# Generated by Django 3.0.3 on 2021-01-31 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eapp', '0005_fillnblanks'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=20)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eapp.Courses')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
